//game constants
export const HOST_GAME = 'HOST_GAME';

export const HOST_GAME_SERVER = 'HOST_GAME_SERVER';

export const JOIN_GAME = 'JOIN_GAME';

export const JOIN_GAME_SERVER = 'JOIN_GAME_SERVER';
export const JOIN_GAME_FAIL_SERVER = 'JOIN_GAME_FAIL_SERVER';

export const SET_CURRENT_PLAYER_SERVER = 'SET_CURRENT_PLAYER_SERVER';

export const START_GAME = 'START_GAME';

export const START_GAME_SERVER = 'START_GAME_SERVER';

export const SET_CURRENT_MOVE = 'SET_CURRENT_MOVE';

export const SEND_CURRENT_GAME_STATE = 'SEND_CURRENT_GAME_STATE';

export const SEND_CURRENT_GAME_STATE_SERVER = 'SEND_CURRENT_GAME_STATE_SERVER';

export const SHOW_ROUND_RESULTS_SERVER = 'SHOW_ROUND_RESULTS_SERVER';

export const START_NEXT_ROUND = 'START_NEXT_ROUND';

export const RESET_NEXT_ROUND_CURRENT_PLAYER_SERVER =
  'RESET_NEXT_ROUND_CURRENT_PLAYER_SERVER';

export const START_NEXT_ROUND_SERVER = 'START_NEXT_ROUND_SERVER';

export const ALERT_LEAVER = 'ALERT_LEAVER';

export const ALERT_LEAVER_SERVER = 'ALERT_LEAVER_SERVER';
